# Crawling PTA & Berita

### Library

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re, sys, time
from urllib.parse import urljoin, urlparse
import urllib3

## 1. Crawling PTA

In [9]:
BASE_URL = "https://pta.trunojoyo.ac.id/c_search/byprod"

### Fungsi

In [10]:
def get_max_page(prodi_id):
    url = f"{BASE_URL}/{prodi_id}/1"
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")

    # Cari tombol >> (last page)
    last_page = soup.select_one('ol.pagination a:contains("»")')
    if last_page and "href" in last_page.attrs:
        href = last_page["href"]
        # Pecah URL -> ambil angka terakhir
        max_page = int(href.split("/")[-1])
        return max_page

    # fallback kalau pagination tidak ada
    return 1

In [11]:
# Contoh pemakaian
print(get_max_page(10))

172

/usr/local/lib/python3.12/dist-packages/soupsieve/css_parser.py:876: FutureWarning: The pseudo class ':contains' is deprecated, ':-soup-contains' should be used moving forward.
  warnings.warn(  # noqa: B028

In [12]:
def print_progress(prodi_id, prodi, current_page, total_pages):
    percent = (current_page / total_pages) * 100
    bar_length = 20
    filled_length = int(bar_length * current_page // total_pages)
    bar = '█' * filled_length + '-' * (bar_length - filled_length)
    sys.stdout.write(f'\r[{prodi_id}] {prodi} - Page {current_page}/{total_pages} [{bar}] {percent:.2f}%')
    sys.stdout.flush()
    if current_page == total_pages:
        sys.stdout.write('\n')

### Fungsi Crawling Semua Data PTA

### Fungsi Crawling Data PTA

In [ ]:
def print_progress(prodi_id, prodi, current_page, total_pages):
    percent = (current_page / total_pages) * 100
    bar_length = 20
    filled_length = int(bar_length * current_page // total_pages)
    bar = '█' * filled_length + '-' * (bar_length - filled_length)
    sys.stdout.write(f'\r[{prodi_id}] {prodi} - Page {current_page}/{total_pages} [{bar}] {percent:.2f}%')
    sys.stdout.flush()
    if current_page == total_pages:
        sys.stdout.write('\n\n')

def pta():
    start_time = time.time()  # mulai hitung waktu

    data = {
        "id": [],
        "penulis": [],
        "judul": [],
        "abstrak id": [],
        "abstrak en": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "prodi": [],
    }

    for i in range(1, 42):  # jumlah prodi
        total_pages = 5  # jumlah page
        prodi_name = None

        for j in range(1, total_pages + 1):  # loop page
            url = f"https://pta.trunojoyo.ac.id/c_search/byprod/{i}/{j}"
            r = requests.get(url)
            soup = BeautifulSoup(r.content, "html.parser")
            jurnals = soup.select('li[data-cat="#luxury"]')

            isii = soup.select_one('div#begin')
            if not isii:
                continue
            prodi_full = isii.select_one('h2').text.strip()
            prodi = prodi_full.replace("Journal Jurusan ", "")
            if not prodi_name:
                prodi_name = prodi

            for jurnal in jurnals:
                link = jurnal.select_one('a.gray.button')['href']

                # ambil ID dari link PTA
                id_match = re.search(r"/detail/(\d+)", link)
                pta_id = id_match.group(1) if id_match else None

                response = requests.get(link)
                soup1 = BeautifulSoup(response.content, "html.parser")
                isi = soup1.select_one('div#content_journal')

                # Judul
                judul = isi.select_one('a.title').text

                # Penulis
                penulis = isi.select_one('span:contains("Penulis")').text.split(' : ')[1]

                # Pembimbing Pertama
                pembimbing_pertama = isi.select_one('span:contains("Dosen Pembimbing I")').text.split(' : ')[1]

                # Pembimbing Kedua
                pembimbing_kedua = isi.select_one('span:contains("Dosen Pembimbing II")').text.split(' :')[1]

                # Abstrak
                paragraf = isi.select('p[align="justify"]')
                abstrak = paragraf[0].get_text(strip=True) if len(paragraf) > 0 else "N/A"
                abstract = paragraf[1].get_text(strip=True) if len(paragraf) > 1 else "N/A"

                # simpan data
                data["id"].append(pta_id)
                data["penulis"].append(penulis)
                data["judul"].append(judul)
                data["pembimbing_pertama"].append(pembimbing_pertama)
                data["pembimbing_kedua"].append(pembimbing_kedua)
                data["abstrak id"].append(abstrak)
                data["abstrak en"].append(abstract)
                data["prodi"].append(prodi)

            # update progress bar
            print_progress(i, prodi_name, j, total_pages)

    df = pd.DataFrame(data)
    df.to_csv("pta.csv", index=False, encoding="utf-8-sig")

    end_time = time.time()
    elapsed = int(end_time - start_time)
    jam, sisa = divmod(elapsed, 3600)
    menit, detik = divmod(sisa, 60)

    # summary
    print("\n✅ Seluruh data berhasil dikumpulkan!")
    print(f"📊 Total entri: {len(df)}")
    print(f"⏱️ Waktu eksekusi: {jam} jam {menit} menit {detik} detik")

    return df

In [ ]:
pta()

[1] Ilmu Hukum - Page 5/5 [████████████████████] 100.00%

[2] Teknologi Industri Pertanian - Page 5/5 [████████████████████] 100.00%

[3] Agribisnis - Page 5/5 [████████████████████] 100.00%

[4] Agroteknologi - Page 5/5 [████████████████████] 100.00%

[5] Ilmu Kelautan - Page 5/5 [████████████████████] 100.00%

[6] Ekonomi Pembangunan - Page 5/5 [████████████████████] 100.00%

[7] Manajemen - Page 5/5 [████████████████████] 100.00%

[8] Akuntansi - Page 5/5 [████████████████████] 100.00%

[9] Teknik Industri - Page 5/5 [████████████████████] 100.00%

[10] Teknik Informatika - Page 5/5 [████████████████████] 100.00%

[11] Manajemen Informatika - Page 5/5 [████████████████████] 100.00%

[12] Sosiologi - Page 5/5 [████████████████████] 100.00%

[13] Ilmu Komunikasi - Page 5/5 [████████████████████] 100.00%

[14] Psikologi - Page 5/5 [████████████████████] 100.00%

[15] Sastra Inggris - Page 5/5 [████████████████████] 100.00%

[16] Ekonomi Syariah - Page 5/5 [████████████████████] 100.00%

[17] Hukum Bisnis Syariah - Page 5/5 [████████████████████] 100.00%

[18] Pgsd - Page 5/5 [████████████████████] 100.00%

[19] Teknik Multimedia Dan Jaringan - Page 5/5 [████████████████████] 100.00%

[20] Mekatronika - Page 5/5 [████████████████████] 100.00%

[21] D3 Akuntansi - Page 5/5 [████████████████████] 100.00%

[22] Magister Manajemen - Page 5/5 [████████████████████] 100.00%

[23] Teknik Elektro - Page 5/5 [████████████████████] 100.00%

[24] Magister Ilmu Hukum - Page 5/5 [████████████████████] 100.00%

[25] Magister Akuntansi - Page 5/5 [████████████████████] 100.00%

[26] D3 Enterpreneurship - Page 5/5 [████████████████████] 100.00%

[27] Pendidikan Bhs Dan Sastra Indonesia - Page 5/5 [████████████████████] 100.00%

[28] Pendidikan Informatika - Page 5/5 [████████████████████] 100.00%

[29] Pendidikan Ipa - Page 5/5 [████████████████████] 100.00%

[30] Pgpaud - Page 5/5 [████████████████████] 100.00%

[31] Sistem Informasi - Page 5/5 [████████████████████] 100.00%

[32] Teknik Mesin - Page 5/5 [████████████████████] 100.00%

[33] Teknik Mekatronika - Page 5/5 [████████████████████] 100.00%

[34] Journal Jurusan - Page 5/5 [████████████████████] 100.00%

[35] Manajemen Sumberdaya Perairan - Page 5/5 [████████████████████] 100.00%

[36] Magister Ilmu Ekonomi - Page 5/5 [████████████████████] 100.00%

[37] Magister Pengelolaan Sumber Daya Alam - Page 5/5 [████████████████████] 100.00%

[38] Pendidikan Profesi Guru - Page 5/5 [████████████████████] 100.00%

[39] Magister Pendidikan Dasar - Page 5/5 [████████████████████] 100.00%

[40] Doktor Pengelolaan Sumber Daya Alam - Page 5/5 [████████████████████] 100.00%

[41] Doktor Ilmu Manajemen - Page 5/5 [████████████████████] 100.00%


✅ Seluruh data berhasil dikumpulkan!
📊 Total entri: 781
⏱️ Waktu eksekusi: 1 jam 28 menit 55 detik

,id,penulis,judul,abstrak id,abstrak en,pembimbing_pertama,pembimbing_kedua,prodi
0,080111100012,Dyah Ayu Citra Seza,Implementasi Fungsi Legislasi Dewan Perwakilan...,ABSTRAK\r\n\r\n Implementasi Fungsi Legi...,ABSTRACT\r\n Implementation of Legislati...,"Yudi Widagdo Harimurti, SH., MH","Safi', SH., MH",Ilmu Hukum
1,080111100002,Maulina Nurlaily,Pertanggungjawaban Pidana Direksi BUMN (Perser...,Badan Usaha Milik Negara (BUMN) adalah Badan u...,State Owned Enterprises (SOEs) are business en...,"Tolib Effendi, SH., MH.","Dr. Eni Suastuti, SH., Mhum.",Ilmu Hukum
2,070111100060,Moh. Samsul Hidayat,Analisis Terhadap Kekosongan Hukum dalam Penga...,Kasus narkoba tidak henti-hentinya terdengar d...,"Drug cases endlessly heard on television, radi...","Tolib Effendi, SH., MH.","Agus Ramdlany, SH., MH.",Ilmu Hukum
3,090111100077,TOMMY ADITYA PARLINDUNGAN MARBUN,PERLINDUNGAN HUKUM BAGI KONSUMEN ATAS PRODUK E...,Produk elektronik adalah suatu benda bergerak ...,Electronic products is an object moves through...,"DR. DJULAEKA, S.H., M.HUM","DR.USWATUN HASANAH, S.H., M. HUM",Ilmu Hukum
4,070111200007,RICA YENA IMADHORA,TELAAH KRITIS TENTANG ALASAN HUKUM YANG DIGUN...,,,"Dr. DENI SBY, S. H., M. S.","SAIFUL ABDULLAH, S. H., M. H.",Ilmu Hukum
...,...,...,...,...,...,...,...,...
776,160281100013,"Lisa Sri rahmatullah, S. Sos. I",Dampak Sosial Ekonomi Pariwisata Religi Makam ...,Penelitian ini bertujuan untuk mengetahui baga...,The purpose of this study is to analyze the so...,"Dr. Diah Wahyuningsih, S.E., M.Si.","Dr. Eni Sri Rahayuningsih, S.E., M.E.",Magister Ilmu Ekonomi
777,160281100002,Indah Ainun Nikmah,Peranan Zakat Produktif Dalam Meningkatkan Eko...,Peranan Zakat Produktif dalam Meningkatkan Eko...,The Role of Productive Zakat in Improving Must...,"Dr. Kurniyati Indahsari, M.Si","Dr. Abdur Rahman, S.Ag. MEI",Magister Ilmu Ekonomi
778,170361100010,ahmad syaiful umam,KARAKTERISASI DAN KOLEKSI PLASMA NUTFAH UNTUK ...,Madura merupakan salah satu wilayah pemasok ko...,Madura is one of the regions supplying horticu...,"Dr. Ir. Gita Pawana, M.Si","Dr. Ir. Hj. SIti Fatimah, M.Si",Magister Pengelolaan Sumber Daya Alam
779,170361100001,Siti Holifah,PENGOLAHAN LIMBAH AIR REBUSAN IKAN TERI MENJAD...,Ikan Teri perlu penanganan serius pasca panen ...,Anchovy needs serious handling after harvest b...,"Dr.Apri Arisandi,S.Pi.,M.Si.","Dr.Ir.H.Asfan,MP.",Magister Pengelolaan Sumber Daya Alam
780,170361100003,Mohammad Maskur,STRATEGI PENGEMBANGAN MAKANAN DAN MINUMAN KHAS...,Makanan dan minuman khas merupakan ciri dari k...,Typical food and drinks are characteristic of ...,"Dr. Akhmad Farid, S.Pi., MT","Dr. Apri Arisandi, S.Pi., M.Si",Magister Pengelolaan Sumber Daya Alam

## Page & Link Keluar PTA

In [ ]:



# matikan warning SSL insecure
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def scrape_all_links(base_url, max_pages=50):
    visited = set()
    results = []

    def scrape_page(url):
        try:
            response = requests.get(url, verify=False, timeout=10)
            soup = BeautifulSoup(response.text, 'html.parser')

            # ambil semua link keluar
            for a in soup.find_all('a', href=True):
                href = a['href'].strip()
                if not href or href == "#":
                    continue
                full_link = urljoin(url, href)
                results.append({
                    "Page": url,
                    "Link Keluar": full_link
                })

            # cari link internal untuk dilanjutkan
            for a in soup.find_all('a', href=True):
                href = a['href'].strip()
                if not href or href == "#":
                    continue
                full_link = urljoin(url, href)
                # hanya ambil link internal (masih di domain utama)
                if full_link.startswith(base_url) and full_link not in visited:
                    visited.add(full_link)
                    if len(visited) < max_pages:
                        scrape_page(full_link)

        except Exception as e:
            print(f"⚠️ Gagal akses {url}: {e}")

    # mulai dari base_url
    visited.add(base_url)
    scrape_page(base_url)

    # rapikan dataframe
    df = pd.DataFrame(results).reset_index(drop=True)
    df.index += 1
    df.insert(0, "No", df.index)
    return df

# contoh penggunaan
url = "https://informatika.trunojoyo.ac.id/"
df_links = scrape_all_links(url, max_pages=30)  # max_pages = batas biar ga infinite loop

df_links
# df_links.to_csv("semua_link.csv", index=False, encoding="utf-8-sig")

,No,Page,Link Keluar
1,1,https://informatika.trunojoyo.ac.id/,https://informatika.trunojoyo.ac.id/
2,2,https://informatika.trunojoyo.ac.id/,https://informatika.trunojoyo.ac.id/bidang-min...
3,3,https://informatika.trunojoyo.ac.id/,https://informatika.trunojoyo.ac.id/bidang-min...
4,4,https://informatika.trunojoyo.ac.id/,https://informatika.trunojoyo.ac.id/bidang-min...
5,5,https://informatika.trunojoyo.ac.id/,https://informatika.trunojoyo.ac.id/bidang-min...
...,...,...,...
1704,1704,https://informatika.trunojoyo.ac.id/unit-kegia...,https://ukmfteecom.vercel.app/
1705,1705,https://informatika.trunojoyo.ac.id/unit-kegia...,https://informatika.trunojoyo.ac.id/berita-pro...
1706,1706,https://informatika.trunojoyo.ac.id/unit-kegia...,https://informatika.trunojoyo.ac.id/berita-pro...
1707,1707,https://informatika.trunojoyo.ac.id/unit-kegia...,https://informatika.trunojoyo.ac.id/berita-pro...
1708,1708,https://informatika.trunojoyo.ac.id/unit-kegia...,https://informatika.trunojoyo.ac.id/berita-pro...

In [ ]:
def print_progress(prodi_id, prodi, current_page, total_pages):
    percent = (current_page / total_pages) * 100
    bar_length = 20
    filled_length = int(bar_length * current_page // total_pages)
    bar = '█' * filled_length + '-' * (bar_length - filled_length)
    sys.stdout.write(f'\r[{prodi_id}] {prodi} - Page {current_page}/{total_pages} [{bar}] {percent:.2f}%')
    sys.stdout.flush()
    if current_page == total_pages:
        sys.stdout.write('\n\n')

def pta_links():
    start_time = time.time()  # mulai hitung waktu

    data = {
        "no": [],
        "page": [],
        "link_keluar": []
    }

    no = 1  # nomor urut

    for i in range(1, 42):  # jumlah prodi
        total_pages = 5  # jumlah page
        prodi_name = None

        for j in range(1, total_pages + 1):  # loop page
            url = f"https://pta.trunojoyo.ac.id/c_search/byprod/{i}/{j}"
            r = requests.get(url)
            soup = BeautifulSoup(r.content, "html.parser")
            jurnals = soup.select('li[data-cat="#luxury"]')

            isii = soup.select_one('div#begin')
            if not isii:
                continue
            prodi_full = isii.select_one('h2').text.strip()
            prodi = prodi_full.replace("Journal Jurusan ", "")
            if not prodi_name:
                prodi_name = prodi

            for jurnal in jurnals:
                link = jurnal.select_one('a.gray.button')['href']

                data["no"].append(no)
                data["page"].append(url)          # link page
                data["link_keluar"].append(link)  # link detail
                no += 1

            # update progress bar
            print_progress(i, prodi_name, j, total_pages)

    df = pd.DataFrame(data)
    df.to_csv("pta_links.csv", index=False)

    end_time = time.time()
    elapsed = int(end_time - start_time)
    jam, sisa = divmod(elapsed, 3600)
    menit, detik = divmod(sisa, 60)

    # summary
    print("\n✅ Seluruh link berhasil dikumpulkan!")
    print(f"📊 Total entri: {len(df)}")
    print(f"⏱️ Waktu eksekusi: {jam} jam {menit} menit {detik} detik")

    return df

In [ ]:
pta_links()

[1] Ilmu Hukum - Page 3/3 [████████████████████] 100.00%

[2] Teknologi Industri Pertanian - Page 3/3 [████████████████████] 100.00%

[3] Agribisnis - Page 3/3 [████████████████████] 100.00%

[4] Agroteknologi - Page 3/3 [████████████████████] 100.00%

[5] Ilmu Kelautan - Page 3/3 [████████████████████] 100.00%

[6] Ekonomi Pembangunan - Page 3/3 [████████████████████] 100.00%

[7] Manajemen - Page 3/3 [████████████████████] 100.00%

[8] Akuntansi - Page 3/3 [████████████████████] 100.00%

[9] Teknik Industri - Page 3/3 [████████████████████] 100.00%

[10] Teknik Informatika - Page 3/3 [████████████████████] 100.00%

[11] Manajemen Informatika - Page 3/3 [████████████████████] 100.00%

[12] Sosiologi - Page 3/3 [████████████████████] 100.00%

[13] Ilmu Komunikasi - Page 3/3 [████████████████████] 100.00%

[14] Psikologi - Page 3/3 [████████████████████] 100.00%

[15] Sastra Inggris - Page 3/3 [████████████████████] 100.00%

[16] Ekonomi Syariah - Page 3/3 [████████████████████] 100.00%

[17] Hukum Bisnis Syariah - Page 3/3 [████████████████████] 100.00%

[18] Pgsd - Page 3/3 [████████████████████] 100.00%

[19] Teknik Multimedia Dan Jaringan - Page 3/3 [████████████████████] 100.00%

[20] Mekatronika - Page 3/3 [████████████████████] 100.00%

[21] D3 Akuntansi - Page 3/3 [████████████████████] 100.00%

[22] Magister Manajemen - Page 3/3 [████████████████████] 100.00%

[23] Teknik Elektro - Page 3/3 [████████████████████] 100.00%

[24] Magister Ilmu Hukum - Page 3/3 [████████████████████] 100.00%

[25] Magister Akuntansi - Page 3/3 [████████████████████] 100.00%

[26] D3 Enterpreneurship - Page 3/3 [████████████████████] 100.00%

[27] Pendidikan Bhs Dan Sastra Indonesia - Page 3/3 [████████████████████] 100.00%

[28] Pendidikan Informatika - Page 3/3 [████████████████████] 100.00%

[29] Pendidikan Ipa - Page 3/3 [████████████████████] 100.00%

[30] Pgpaud - Page 3/3 [████████████████████] 100.00%

[31] Sistem Informasi - Page 3/3 [████████████████████] 100.00%

[32] Teknik Mesin - Page 3/3 [████████████████████] 100.00%

[33] Teknik Mekatronika - Page 3/3 [████████████████████] 100.00%

[34] Journal Jurusan - Page 3/3 [████████████████████] 100.00%

[35] Manajemen Sumberdaya Perairan - Page 3/3 [████████████████████] 100.00%

[36] Magister Ilmu Ekonomi - Page 3/3 [████████████████████] 100.00%

[37] Magister Pengelolaan Sumber Daya Alam - Page 3/3 [████████████████████] 100.00%

[38] Pendidikan Profesi Guru - Page 3/3 [████████████████████] 100.00%

[39] Magister Pendidikan Dasar - Page 3/3 [████████████████████] 100.00%

[40] Doktor Pengelolaan Sumber Daya Alam - Page 3/3 [████████████████████] 100.00%

[41] Doktor Ilmu Manajemen - Page 3/3 [████████████████████] 100.00%


✅ Seluruh link berhasil dikumpulkan!
📊 Total entri: 481
⏱️ Waktu eksekusi: 0 jam 5 menit 1 detik

,no,page,link_keluar
0,1,https://pta.trunojoyo.ac.id/c_search/byprod/1/1,https://pta.trunojoyo.ac.id/welcome/detail/080...
1,2,https://pta.trunojoyo.ac.id/c_search/byprod/1/1,https://pta.trunojoyo.ac.id/welcome/detail/080...
2,3,https://pta.trunojoyo.ac.id/c_search/byprod/1/1,https://pta.trunojoyo.ac.id/welcome/detail/070...
3,4,https://pta.trunojoyo.ac.id/c_search/byprod/1/1,https://pta.trunojoyo.ac.id/welcome/detail/090...
4,5,https://pta.trunojoyo.ac.id/c_search/byprod/1/1,https://pta.trunojoyo.ac.id/welcome/detail/070...
...,...,...,...
476,477,https://pta.trunojoyo.ac.id/c_search/byprod/36/2,https://pta.trunojoyo.ac.id/welcome/detail/160...
477,478,https://pta.trunojoyo.ac.id/c_search/byprod/36/2,https://pta.trunojoyo.ac.id/welcome/detail/160...
478,479,https://pta.trunojoyo.ac.id/c_search/byprod/37/1,https://pta.trunojoyo.ac.id/welcome/detail/170...
479,480,https://pta.trunojoyo.ac.id/c_search/byprod/37/1,https://pta.trunojoyo.ac.id/welcome/detail/170...
480,481,https://pta.trunojoyo.ac.id/c_search/byprod/37/1,https://pta.trunojoyo.ac.id/welcome/detail/170...

## 2. Crawling Berita

### Fungsi

### Crawling Berita

In [ ]:
import requests, re, time, sys
from bs4 import BeautifulSoup
import pandas as pd

def get_article_content(url, max_sentences=2):
    r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
    soup = BeautifulSoup(r.text, "html.parser")

    content_div = soup.find("div", id="content-wrapper")
    if content_div:
        paragraphs = content_div.find_all("p")
    else:
        paragraphs = soup.find_all("p")  # fallback

    first_paragraph = ""
    for p in paragraphs:
        text = re.sub(r"\s+", " ", p.get_text(" ", strip=True))
        if text and not text.lower().startswith("baca juga"):
            first_paragraph = text
            break  # cukup ambil 1 paragraf pertama

    sentences = re.split(r'(?<=[.!?])\s+', first_paragraph)
    return " ".join(sentences[:max_sentences])


def berita(categories, pages_per_category=1):
    start_time = time.time()
    BASE_URL = "https://www.cnnindonesia.com/indeks?page={}&category=rubrik&rubric_slug={}"

    data = {"id_berita": [], "judul_berita": [], "isi_berita": [], "kategori_berita": []}
    total_task = len(categories) * pages_per_category
    done = 0

    for cat in categories:
        for page in range(1, pages_per_category+1):
            url = BASE_URL.format(page, cat)
            r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
            soup = BeautifulSoup(r.text, "html.parser")

            articles = soup.select("article h2.title a") or soup.select("article a")
            for a in articles:
                link = a["href"]
                if not link.startswith("http"):
                    link = "https://www.cnnindonesia.com" + link

                id_match = re.search(r"/(\d{14}-\d+-\d+)/", link)
                if not id_match:
                    continue
                berita_id = id_match.group(1)

                title = a.get_text(strip=True) or a.get("title", "")

                try:
                    content = get_article_content(link)
                except:
                    content = ""

                data["id_berita"].append(berita_id)
                data["judul_berita"].append(title)
                data["isi_berita"].append(content)
                data["kategori_berita"].append(cat)

            done += 1
            progress = int((done / total_task) * 30)
            bar = "█" * progress + "-" * (30 - progress)
            percent = (done / total_task) * 100
            sys.stdout.write(f"\r[{bar}] {percent:6.2f}% (kategori {cat}, halaman {page})")
            sys.stdout.flush()

    df = pd.DataFrame(data)
    df.to_csv("cnn_berita.csv", index=False, encoding="utf-8-sig")

    print("\n✅ Selesai! Total berita:", len(df))
    print(f"⏱️ Durasi: {round(time.time() - start_time,2)} detik")
    return df

# contoh
categories = ["nasional", "ekonomi", "internasional","teknologi","otomotif"]

In [ ]:
berita(categories, pages_per_category=2)

[██████████████████████████████] 100.00% (kategori otomotif, halaman 2)
✅ Selesai! Total berita: 100
⏱️ Durasi: 36.58 detik

,id_berita,judul_berita,isi_berita,kategori_berita
0,20250911120703-25-1272509,Kementerian PU Buka Akses Jalan Nasional Terda...,Kementerian Pekerjaan Umum (PU) menyatakan tel...,nasional
1,20250911121747-20-1272516,"Update Banjir Bali: 14 Tewas, 2 Hilang, 562 Wa...",Badan Nasional Penanggulangan Bencana (BNPB) m...,nasional
2,20250911115014-12-1272503,Keluarga Ojol Tewas saat Rusuh Makassar Tolak ...,"Keluarga pengemudi ojek online, Rusdamdiansyah...",nasional
3,20250910121451-307-1272092,The Gramercy: Kesempatan Terakhir Miliki Rumah...,Alam Sutera kembali menegaskan posisinya sebag...,nasional
4,20250911114128-24-1272498,01:01VIDEO: Atap Gedung SMKN 1 Cileungsi Roboh...,Puluhan siswa SMKN 1 Cileungsi mengalami luka ...,nasional
...,...,...,...,...
95,20250911111236-142-1272486,Kapan Indonesia Main di Babak 4 Kualifikasi Pi...,Timnas Indonesia akan berjuang di babak keempa...,otomotif
96,20250910161430-260-1272216,Sebab Nyeri Dada Saat Olahraga: Asam Lambung h...,Mengalami nyeri dada setelah olahraga memang b...,otomotif
97,20250911110902-402-1272487,02:16VIDEO: Presiden Prabowo Hadiri BRICS Virt...,"Presiden RI Prabowo Subianto pada Senin, 8 Sep...",otomotif
98,20250911113000-134-1272494,"Ironi Charlie Kirk, Pendukung Kepemilikan Senj...",Aktivis sayap kanan sekaligus loyalis Presiden...,otomotif
99,20250911110158-12-1272483,Kakak Hary Tanoe Tersangka Kasus Korupsi Penya...,Kakak dari Pendiri Partai Perindo Hary Tanoeso...,otomotif